# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user1@gmail.local",
  "dateBirth": "2012-02-22",
  "firstname": "Nike",
  "lastname": "Smith",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/12f372c5-c331-49a8-b37b-33172d15c1c2 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user1@gmail.local",
  "password": "123456"
}
